version: "3"
services:
  mariadb:
    container_name: mariadb-api-ifood-ibtlvrptest
    image: "mariadb:latest"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ifood-ibtlvrptest'
